FROM node:lts-alpine
ARG MODE

# Install simple HTTP server for serving static content
RUN npm install -g http-server

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the project files to the working directory
COPY . .

# Build the app with the specified mode
RUN npm run build -- --mode ${MODE}

# Expose port 8080
EXPOSE 8080

# Start the server
CMD [ "http-server", "dist" ]
